name: Тесты

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  test:
    uses: autumn-library/workflows/.github/workflows/test.yml@main
    with:
      test_engine: oneunit
      test_dir_paths: tests
      test_recursive: true
